### PR TITLE
Support for Kubernetes 1.14

### PR DESCRIPTION
**Pull request by mkjpryor-stfc**
And drop support for 1.12.

Add a gate to check for supported versions.

### CODE REVIEW

**Review by brtkwr — APPROVED** [review]
Nice work!

**Review by brtkwr — COMMENTED** [review]
Is this backward compatible with 1.13?

**Comment by mkjpryor-stfc** [comment]
@brtknr 

Yes. But not 1.12, hence why it's not in the supported versions...!

**Comment by mkjpryor-stfc** [comment]
Once the kubeadm config files become GA, I'll probably have to try and think of a good way to produce different config files for different versions. But that's for another day... :)

**Pull request merged**
